export const initialState = {
  Products: [
    {
      id: 1,
      name: 'Classic White T-Shirt',
      description: 'A timeless and comfortable white t-shirt made from 100% cotton. Perfect for everyday wear and easy to pair with any outfit.',
      price: 19.99,
      category: 'Apparel',
      image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQlnOeeTTp_u6Vu34vGU-PUghhpzLzxr3_jPzRczX0vCDlq-lgG-QTUpV77IreUvvxBDiSZNF2vTH1dLSVCfqpfcPR68zFZ4rDMsxhMCFZt',
      inCartQt: 0,
    },
    {
      id: 2,
      name: 'Bluetooth Earbuds',
      description: 'High-quality wireless earbuds with noise isolation and long-lasting battery life. Ideal for workouts, travel, and daily use.',
      price: 49.99,
      category: 'Electronics',
      image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSK5Zl9_SfAxur-1OVtv0dTlX4j57OyKW_QPfd7vuEwSwRbyf_f5Fv1fG5BtxsJDA3CGE5_Ohq_Rbr_q_cUmne67fHCgEGX7Q2uwPqRZQmM',
      inCartQt: 0,
    },
    {
      id: 3,
      name: 'Gaming Mouse',
      description: 'Precision gaming mouse with customizable DPI, RGB lighting, and ergonomic design for extended gaming sessions.',
      price: 29.99,
      category: 'Electronics',
      image: 'https://m.media-amazon.com/images/I/31RYQTatwkL._AC._SR180,230.jpg',
      inCartQt: 0,
    },
    {
      id: 4,
      name: 'Leather Wallet',
      description: 'Premium leather wallet with multiple card slots and a sleek, compact design. A stylish and functional accessory.',
      price: 24.99,
      category: 'Accessories',
      image: 'data:image/jpeg;base64,...',
      inCartQt: 0,
    },
    {
      id: 5,
      name: 'Stainless Steel Water Bottle',
      description: 'Durable and eco-friendly water bottle with double-wall insulation to keep drinks hot or cold for hours.',
      price: 15.99,
      category: 'Home & Kitchen',
      image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRHEtqPWJS6SsExuKITnUZEMV5TSOwccYhAFs9ScCA-3Ts8F1M6j726qfHNYeTmutNlHmJon5PcwtHB1GKdQBMUz6IXWacQMu6VLOPwZ8Me',
      inCartQt: 0,
    },
    {
      id: 6,
      name: 'Yoga Mat',
      description: 'Non-slip yoga mat with cushioning support for all types of floor exercises. Lightweight and easy to carry.',
      price: 22.49,
      category: 'Fitness',
      image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQk_C44PQPuVrzA1IFo5pSSWIcsIjJOpuzfwTTOX9rxcltHztH9RjL-mZkCLEnGPSKMkFj69IUthNTinsj4I1YjNSXozcg892YfPtqZlj80VtfpZYj0E7HbVQ',
      inCartQt: 0,
    },
    {
      id: 7,
      name: 'Smartwatch',
      description: 'Feature-packed smartwatch with fitness tracking, notifications, and customizable watch faces. Compatible with iOS and Android.',
      price: 149.99,
      category: 'Wearables',
      image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTRC2hk2O7jO65P9vI3ODExp7b2qeSLNkl-w7zto5KDbtXqtfWT5YJsLIjQ6R6_WvOmxKADlkhiljTrWjn2Cjj_8IJTeMk0YRLyKweIcaPQ4NB8mFXP2PFLcw',
      inCartQt: 0,
    },
    {
      id: 8,
      name: 'Noise Cancelling Headphones',
      description: 'Over-ear headphones with active noise cancellation and immersive sound. Ideal for travel or focused work.',
      price: 89.99,
      category: 'Electronics',
      image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSH-L1wptEWh_pqtT02_z_3VR0N31W7Glad3erC8ElPv9Jk9UI4AwmPRhZ_LEp5r6FJyR5BTiMTh9R5ZI7I9bHOegW8d_3PrpB27t8j8gOx',
      inCartQt: 0,
    },
    {
      id: 9,
      name: '4K Action Camera',
      description: 'Compact and rugged 4K action camera with waterproof housing and wide-angle lens. Great for capturing adventures.',
      price: 129.99,
      category: 'Cameras',
      image: 'https://example.com/images/action-camera.jpg',
      inCartQt: 0,
    },
    {
      id: 10,
      name: 'Laptop Backpack',
      description: 'Spacious and padded laptop backpack with multiple compartments. Water-resistant and comfortable to wear.',
      price: 39.99,
      category: 'Bags',
      image: 'https://example.com/images/laptop-backpack.jpg',
      inCartQt: 0,
    },
    {
      id: 11,
      name: 'Running Shoes',
      description: 'Lightweight and breathable running shoes with cushioned soles for comfort and performance.',
      price: 59.99,
      category: 'Footwear',
      image: 'https://example.com/images/running-shoes.jpg',
      inCartQt: 0,
    },
    {
      id: 12,
      name: 'Drawing Tablet',
      description: 'Digital drawing tablet with pressure sensitivity and customizable buttons. Ideal for artists and designers.',
      price: 99.99,
      category: 'Electronics',
      image: 'https://example.com/images/drawing-tablet.jpg',
      inCartQt: 0,
    },
    {
      id: 13,
      name: 'Ceramic Coffee Mug',
      description: 'Stylish ceramic mug with a comfortable handle. Microwave and dishwasher safe — perfect for daily coffee or tea.',
      price: 12.49,
      category: 'Home & Kitchen',
      image: 'https://example.com/images/coffee-mug.jpg',
      inCartQt: 0,
    },
    {
      id: 14,
      name: 'LED Desk Lamp',
      description: 'Adjustable LED desk lamp with touch controls, brightness settings, and energy-efficient lighting.',
      price: 27.99,
      category: 'Home & Lighting',
      image: 'https://example.com/images/desk-lamp.jpg',
      inCartQt: 0,
    },
    {
      id: 15,
      name: 'Men’s Casual Jacket',
      description: 'Stylish men’s jacket suitable for casual outings and chilly weather. Features a comfortable inner lining.',
      price: 64.99,
      category: 'Apparel',
      image: 'https://example.com/images/mens-jacket.jpg',
      inCartQt: 0,
    },
    {
      id: 16,
      name: 'Women’s Handbag',
      description: 'Elegant and versatile handbag for women. Includes multiple compartments and a sleek, modern design.',
      price: 49.99,
      category: 'Accessories',
      image: 'https://example.com/images/womens-handbag.jpg',
      inCartQt: 0,
    },
    {
      id: 17,
      name: 'Electric Toothbrush',
      description: 'Rechargeable electric toothbrush with multiple cleaning modes and a two-minute timer for optimal oral care.',
      price: 39.99,
      category: 'Personal Care',
      image: 'https://example.com/images/electric-toothbrush.jpg',
      inCartQt: 0,
    },
    {
      id: 18,
      name: 'Power Bank',
      description: 'Portable power bank with fast-charging capability and high-capacity battery — keep your devices charged on the go.',
      price: 25.99,
      category: 'Electronics',
      image: 'https://example.com/images/power-bank.jpg',
      inCartQt: 0,
    },
    {
      id: 19,
      name: 'Travel Pillow',
      description: 'Ergonomic neck pillow designed for maximum comfort during travel. Compact and lightweight for easy packing.',
      price: 18.99,
      category: 'Travel',
      image: 'https://example.com/images/travel-pillow.jpg',
      inCartQt: 0,
    },
    {
      id: 20,
      name: 'Fitness Tracker',
      description:' Sleek fitness tracker with heart rate monitoring, step counting, and sleep tracking. Syncs with your smartphone for detailed insights.',
      price: 59.99,
      category: 'Wearables',
      image: 'https://example.com/images/fitness-tracker.jpg',
      inCartQt: 0,
    },
  ],
};
